version: 1
updates:
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
      time: "13:00"
      timezone: America/Los_Angeles
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: node
        versions:
          - 16.16.0
          - 15.10.0
          - 15.11.0
          - 15.12.0
          - 15.13.0
          - 15.14.0
          - 15.7.0
          - 15.8.0
          - 15.9.0
